### PR TITLE
persistent phantoms

### PR DESCRIPTION
**Pull request by blue0513**
https://github.com/blue0513/phantom-inline-comment/issues/12

* [x] Dump phantoms into some files
* [x] Restore phantoms from files
* [x] Make minor-mode to enable these options
* [x] Check it works!

### CODE REVIEW

**Comment by alphapapa** [comment]
Ideally this could be a minor-mode that would read e.g. hidden files in the same directory as the source file.

**Comment by blue0513** [comment]
@alphapapa Thx for your advice! (I'm a fan of your package, [yequake](https://github.com/alphapapa/yequake) and so)

> hidden files in the same directory as the source file

Hmm....what does that mean specifically? (Sorry for my poor English skills)  
In this branch (still WIP), the file which contains the stored phantom-inline-comments will be saved as [`~/.phantom-inline-comments`](https://github.com/blue0513/phantom-inline-comment/blob/feature/persistent-phantoms/phantom-inline-comment.el#L48). You mean, the each file should have each stored phantom-inline-comments file like below?
```
├── dirA
   ├── file_A
   ├── .file_A.phantom  <== including phantom-inline-comments for file_A
   ├── file_B
```

**Comment by alphapapa** [comment]
Thanks for the kind words.  Glad you find them useful.

> You mean, the each file should have each stored phantom-inline-comments file like below?

Sure, that's one option.  Another would be per-directory hidden files.  Using one file per file would make it easier to keep files and comments in sync, of course, but the user would still be responsible for moving the associated comment file when moving a source file.

IMO using one file in the user's home directory doesn't make sense, because I think the comments ought to be stored in the repo with the source files.  The user can decide whether to commit them or keep them locally.  In that vein, you should probably imitate `dir-locals` and support an equivalent of `dir-locals2.el` for user-local changes that aren't to be committed to VCS.

**Comment by blue0513** [comment]
> Sure, that's one option. Another would be per-directory hidden files
> the comments ought to be stored in the repo with the source files

Good! Happy to hear your advice! :+1:
Yeah, as you said, the comment-files should be much more controllable/observable for users.

I thought it should be option for users to select the style: only one file in home directory, the files in each dir or for each source file, because probably some users want to separate the comment-files from source files/dirs but others not.

Ok, in this PR, I'll implement "only one file in home directory" style. And in other PRs, I'll try other styles: "files in each dir", "files for each source file".

**Comment by blue0513** [comment]
@alphapapa Thx for your great help, I could merge this PR as a first experimental function.  
Your suggestion is reflected on #21 👍 and I'll try implement it!

**Pull request merged**
