### PR TITLE
use `locate-user-emacs-file` to specify default save file

### PR DESCRIPTION
**Pull request by conao3**
Hi! This package is awesome!
I found a small issue as the Elisp package, I fix it.

---

It is recommended that Elisp packages save files in user-emacs-directory.
The default value for it is `~/.emacs.d/`, and it has been changed by the user,
`locate-user-emacs-file` is returns path in consideration of the change.

And `locate-user-emacs-file` returns previous path if file exist in HOME,
this change is not destructive.

cf: http://emacs.rubikitch.com/new-files/

Best,

### CODE REVIEW

**Comment by blue0513** [comment]
@conao3 Thx! I didn't know such a custom for Elisp package :eyes:  
Could you modify [README.md#L80](https://github.com/blue0513/phantom-inline-comment/blob/master/README.md#L80) too? 

IMO: like this?
```
"default `~/.emacs.d/pahtnom-inline-comment` or `~/.phantom-inline-comment` if it exists"
```

**Comment by conao3** [comment]
Thank you for your advice! I reflected that advice.

**Comment by blue0513** [comment]
LGTM 👍  
Plz squash these two commits into one commits, then I'll merge this PR!

**Comment by conao3** [comment]
squashed! :)

**Comment by blue0513** [comment]
Thx! merged! 🎉

**Pull request merged**
